@startuml

title __APP's Class Diagram__\n

  namespace androidx.databinding {
    class androidx.databinding.DataBinderMapperImpl {
    }
  }
  

  namespace androidx.databinding {
    interface androidx.databinding.DataBindingComponent {
    }
  }
  

  namespace androidx.databinding {
    namespace library.baseAdapters {
      class androidx.databinding.library.baseAdapters.BR {
      }
    }
  }
  

  namespace com.example.starwarslib {
    class com.example.starwarslib.BR {
    }
  }
  

  namespace com.example.starwarslib {
    class com.example.starwarslib.BuildConfig {
    }
  }
  

  namespace com.example.starwarslib {
    class com.example.starwarslib.DataBinderMapperImpl {
    }
  }
  

  namespace com.example.starwarslib {
    namespace database {
      class com.example.starwarslib.database.CharactersDao_Impl {
      }
    }
  }
  

  namespace com.example.starwarslib {
    namespace database {
      class com.example.starwarslib.database.EntityDatabase_Impl {
      }
    }
  }
  

  namespace com.example.starwarslib {
    namespace database {
      class com.example.starwarslib.database.FilmsDao_Impl {
      }
    }
  }
  

  namespace com.example.starwarslib {
    namespace database {
      class com.example.starwarslib.database.PlanetsDao_Impl {
      }
    }
  }
  

  namespace com.example.starwarslib {
    namespace database {
      class com.example.starwarslib.database.SpeciesDao_Impl {
      }
    }
  }
  

  namespace com.example.starwarslib {
    namespace database {
      class com.example.starwarslib.database.StarshipsDao_Impl {
      }
    }
  }
  

  namespace com.example.starwarslib {
    namespace database {
      class com.example.starwarslib.database.VehiclesDao_Impl {
      }
    }
  }
  

  namespace com.example.starwarslib {
    namespace databinding {
      class com.example.starwarslib.databinding.FragmentDetailBindingImpl {
      }
    }
  }
  

  namespace com.example.starwarslib {
    namespace databinding {
      class com.example.starwarslib.databinding.FragmentListBindingImpl {
      }
    }
  }
  

  namespace com.example.starwarslib {
    namespace databinding {
      class com.example.starwarslib.databinding.GridViewItemBindingImpl {
      }
    }
  }
  

  namespace com.example.starwarslib {
    namespace detail {
      class com.example.starwarslib.detail.DetailFragmentArgs {
      }
    }
  }
  

  namespace com.example.starwarslib {
    namespace list {
      class com.example.starwarslib.list.ListFragmentDirections {
      }
    }
  }
  

  androidx.databinding.DataBinderMapperImpl -up-|> androidx.databinding.MergedDataBinderMapper
  com.example.starwarslib.DataBinderMapperImpl -up-|> androidx.databinding.DataBinderMapper
  com.example.starwarslib.database.CharactersDao_Impl .up.|> com.example.starwarslib.database.CharactersDao
  com.example.starwarslib.database.EntityDatabase_Impl -up-|> com.example.starwarslib.database.EntityDatabase
  com.example.starwarslib.database.EntityDatabase_Impl o-- com.example.starwarslib.database.CharactersDao : _charactersDao
  com.example.starwarslib.database.EntityDatabase_Impl o-- com.example.starwarslib.database.FilmsDao : _filmsDao
  com.example.starwarslib.database.EntityDatabase_Impl o-- com.example.starwarslib.database.PlanetsDao : _planetsDao
  com.example.starwarslib.database.EntityDatabase_Impl o-- com.example.starwarslib.database.SpeciesDao : _speciesDao
  com.example.starwarslib.database.EntityDatabase_Impl o-- com.example.starwarslib.database.StarshipsDao : _starshipsDao
  com.example.starwarslib.database.EntityDatabase_Impl o-- com.example.starwarslib.database.VehiclesDao : _vehiclesDao
  com.example.starwarslib.database.FilmsDao_Impl .up.|> com.example.starwarslib.database.FilmsDao
  com.example.starwarslib.database.PlanetsDao_Impl .up.|> com.example.starwarslib.database.PlanetsDao
  com.example.starwarslib.database.SpeciesDao_Impl .up.|> com.example.starwarslib.database.SpeciesDao
  com.example.starwarslib.database.StarshipsDao_Impl .up.|> com.example.starwarslib.database.StarshipsDao
  com.example.starwarslib.database.VehiclesDao_Impl .up.|> com.example.starwarslib.database.VehiclesDao
  com.example.starwarslib.databinding.FragmentDetailBindingImpl -up-|> com.example.starwarslib.databinding.FragmentDetailBinding
  com.example.starwarslib.databinding.FragmentListBindingImpl -up-|> com.example.starwarslib.databinding.FragmentListBinding
  com.example.starwarslib.databinding.GridViewItemBindingImpl -up-|> com.example.starwarslib.databinding.GridViewItemBinding
  com.example.starwarslib.detail.DetailFragmentArgs .up.|> androidx.navigation.NavArgs


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
